os: linux
dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

script:
  - sudo apt install libsfml-dev
  - cmake .
  - make
