# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ward/Documents/spaceInvaders

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ward/Documents/spaceInvaders

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ward/Documents/spaceInvaders/CMakeFiles /home/ward/Documents/spaceInvaders/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ward/Documents/spaceInvaders/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SI

# Build rule for target.
SI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SI
.PHONY : SI

# fast build rule for target.
SI/fast:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/build
.PHONY : SI/fast

src/controllers/enemy.o: src/controllers/enemy.cpp.o

.PHONY : src/controllers/enemy.o

# target to build an object file
src/controllers/enemy.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/enemy.cpp.o
.PHONY : src/controllers/enemy.cpp.o

src/controllers/enemy.i: src/controllers/enemy.cpp.i

.PHONY : src/controllers/enemy.i

# target to preprocess a source file
src/controllers/enemy.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/enemy.cpp.i
.PHONY : src/controllers/enemy.cpp.i

src/controllers/enemy.s: src/controllers/enemy.cpp.s

.PHONY : src/controllers/enemy.s

# target to generate assembly for a file
src/controllers/enemy.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/enemy.cpp.s
.PHONY : src/controllers/enemy.cpp.s

src/controllers/entity.o: src/controllers/entity.cpp.o

.PHONY : src/controllers/entity.o

# target to build an object file
src/controllers/entity.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/entity.cpp.o
.PHONY : src/controllers/entity.cpp.o

src/controllers/entity.i: src/controllers/entity.cpp.i

.PHONY : src/controllers/entity.i

# target to preprocess a source file
src/controllers/entity.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/entity.cpp.i
.PHONY : src/controllers/entity.cpp.i

src/controllers/entity.s: src/controllers/entity.cpp.s

.PHONY : src/controllers/entity.s

# target to generate assembly for a file
src/controllers/entity.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/entity.cpp.s
.PHONY : src/controllers/entity.cpp.s

src/controllers/physicalEntity.o: src/controllers/physicalEntity.cpp.o

.PHONY : src/controllers/physicalEntity.o

# target to build an object file
src/controllers/physicalEntity.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/physicalEntity.cpp.o
.PHONY : src/controllers/physicalEntity.cpp.o

src/controllers/physicalEntity.i: src/controllers/physicalEntity.cpp.i

.PHONY : src/controllers/physicalEntity.i

# target to preprocess a source file
src/controllers/physicalEntity.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/physicalEntity.cpp.i
.PHONY : src/controllers/physicalEntity.cpp.i

src/controllers/physicalEntity.s: src/controllers/physicalEntity.cpp.s

.PHONY : src/controllers/physicalEntity.s

# target to generate assembly for a file
src/controllers/physicalEntity.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/physicalEntity.cpp.s
.PHONY : src/controllers/physicalEntity.cpp.s

src/controllers/player.o: src/controllers/player.cpp.o

.PHONY : src/controllers/player.o

# target to build an object file
src/controllers/player.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/player.cpp.o
.PHONY : src/controllers/player.cpp.o

src/controllers/player.i: src/controllers/player.cpp.i

.PHONY : src/controllers/player.i

# target to preprocess a source file
src/controllers/player.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/player.cpp.i
.PHONY : src/controllers/player.cpp.i

src/controllers/player.s: src/controllers/player.cpp.s

.PHONY : src/controllers/player.s

# target to generate assembly for a file
src/controllers/player.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/player.cpp.s
.PHONY : src/controllers/player.cpp.s

src/controllers/world.o: src/controllers/world.cpp.o

.PHONY : src/controllers/world.o

# target to build an object file
src/controllers/world.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/world.cpp.o
.PHONY : src/controllers/world.cpp.o

src/controllers/world.i: src/controllers/world.cpp.i

.PHONY : src/controllers/world.i

# target to preprocess a source file
src/controllers/world.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/world.cpp.i
.PHONY : src/controllers/world.cpp.i

src/controllers/world.s: src/controllers/world.cpp.s

.PHONY : src/controllers/world.s

# target to generate assembly for a file
src/controllers/world.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/controllers/world.cpp.s
.PHONY : src/controllers/world.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/models/bullet.o: src/models/bullet.cpp.o

.PHONY : src/models/bullet.o

# target to build an object file
src/models/bullet.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/bullet.cpp.o
.PHONY : src/models/bullet.cpp.o

src/models/bullet.i: src/models/bullet.cpp.i

.PHONY : src/models/bullet.i

# target to preprocess a source file
src/models/bullet.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/bullet.cpp.i
.PHONY : src/models/bullet.cpp.i

src/models/bullet.s: src/models/bullet.cpp.s

.PHONY : src/models/bullet.s

# target to generate assembly for a file
src/models/bullet.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/bullet.cpp.s
.PHONY : src/models/bullet.cpp.s

src/models/enemy.o: src/models/enemy.cpp.o

.PHONY : src/models/enemy.o

# target to build an object file
src/models/enemy.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/enemy.cpp.o
.PHONY : src/models/enemy.cpp.o

src/models/enemy.i: src/models/enemy.cpp.i

.PHONY : src/models/enemy.i

# target to preprocess a source file
src/models/enemy.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/enemy.cpp.i
.PHONY : src/models/enemy.cpp.i

src/models/enemy.s: src/models/enemy.cpp.s

.PHONY : src/models/enemy.s

# target to generate assembly for a file
src/models/enemy.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/enemy.cpp.s
.PHONY : src/models/enemy.cpp.s

src/models/entity.o: src/models/entity.cpp.o

.PHONY : src/models/entity.o

# target to build an object file
src/models/entity.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/entity.cpp.o
.PHONY : src/models/entity.cpp.o

src/models/entity.i: src/models/entity.cpp.i

.PHONY : src/models/entity.i

# target to preprocess a source file
src/models/entity.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/entity.cpp.i
.PHONY : src/models/entity.cpp.i

src/models/entity.s: src/models/entity.cpp.s

.PHONY : src/models/entity.s

# target to generate assembly for a file
src/models/entity.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/entity.cpp.s
.PHONY : src/models/entity.cpp.s

src/models/explosion.o: src/models/explosion.cpp.o

.PHONY : src/models/explosion.o

# target to build an object file
src/models/explosion.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/explosion.cpp.o
.PHONY : src/models/explosion.cpp.o

src/models/explosion.i: src/models/explosion.cpp.i

.PHONY : src/models/explosion.i

# target to preprocess a source file
src/models/explosion.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/explosion.cpp.i
.PHONY : src/models/explosion.cpp.i

src/models/explosion.s: src/models/explosion.cpp.s

.PHONY : src/models/explosion.s

# target to generate assembly for a file
src/models/explosion.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/explosion.cpp.s
.PHONY : src/models/explosion.cpp.s

src/models/physicalEntity.o: src/models/physicalEntity.cpp.o

.PHONY : src/models/physicalEntity.o

# target to build an object file
src/models/physicalEntity.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/physicalEntity.cpp.o
.PHONY : src/models/physicalEntity.cpp.o

src/models/physicalEntity.i: src/models/physicalEntity.cpp.i

.PHONY : src/models/physicalEntity.i

# target to preprocess a source file
src/models/physicalEntity.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/physicalEntity.cpp.i
.PHONY : src/models/physicalEntity.cpp.i

src/models/physicalEntity.s: src/models/physicalEntity.cpp.s

.PHONY : src/models/physicalEntity.s

# target to generate assembly for a file
src/models/physicalEntity.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/physicalEntity.cpp.s
.PHONY : src/models/physicalEntity.cpp.s

src/models/player.o: src/models/player.cpp.o

.PHONY : src/models/player.o

# target to build an object file
src/models/player.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/player.cpp.o
.PHONY : src/models/player.cpp.o

src/models/player.i: src/models/player.cpp.i

.PHONY : src/models/player.i

# target to preprocess a source file
src/models/player.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/player.cpp.i
.PHONY : src/models/player.cpp.i

src/models/player.s: src/models/player.cpp.s

.PHONY : src/models/player.s

# target to generate assembly for a file
src/models/player.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/player.cpp.s
.PHONY : src/models/player.cpp.s

src/models/shield.o: src/models/shield.cpp.o

.PHONY : src/models/shield.o

# target to build an object file
src/models/shield.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/shield.cpp.o
.PHONY : src/models/shield.cpp.o

src/models/shield.i: src/models/shield.cpp.i

.PHONY : src/models/shield.i

# target to preprocess a source file
src/models/shield.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/shield.cpp.i
.PHONY : src/models/shield.cpp.i

src/models/shield.s: src/models/shield.cpp.s

.PHONY : src/models/shield.s

# target to generate assembly for a file
src/models/shield.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/shield.cpp.s
.PHONY : src/models/shield.cpp.s

src/models/spaceShip.o: src/models/spaceShip.cpp.o

.PHONY : src/models/spaceShip.o

# target to build an object file
src/models/spaceShip.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/spaceShip.cpp.o
.PHONY : src/models/spaceShip.cpp.o

src/models/spaceShip.i: src/models/spaceShip.cpp.i

.PHONY : src/models/spaceShip.i

# target to preprocess a source file
src/models/spaceShip.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/spaceShip.cpp.i
.PHONY : src/models/spaceShip.cpp.i

src/models/spaceShip.s: src/models/spaceShip.cpp.s

.PHONY : src/models/spaceShip.s

# target to generate assembly for a file
src/models/spaceShip.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/spaceShip.cpp.s
.PHONY : src/models/spaceShip.cpp.s

src/models/wave.o: src/models/wave.cpp.o

.PHONY : src/models/wave.o

# target to build an object file
src/models/wave.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/wave.cpp.o
.PHONY : src/models/wave.cpp.o

src/models/wave.i: src/models/wave.cpp.i

.PHONY : src/models/wave.i

# target to preprocess a source file
src/models/wave.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/wave.cpp.i
.PHONY : src/models/wave.cpp.i

src/models/wave.s: src/models/wave.cpp.s

.PHONY : src/models/wave.s

# target to generate assembly for a file
src/models/wave.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/wave.cpp.s
.PHONY : src/models/wave.cpp.s

src/models/world.o: src/models/world.cpp.o

.PHONY : src/models/world.o

# target to build an object file
src/models/world.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/world.cpp.o
.PHONY : src/models/world.cpp.o

src/models/world.i: src/models/world.cpp.i

.PHONY : src/models/world.i

# target to preprocess a source file
src/models/world.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/world.cpp.i
.PHONY : src/models/world.cpp.i

src/models/world.s: src/models/world.cpp.s

.PHONY : src/models/world.s

# target to generate assembly for a file
src/models/world.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/models/world.cpp.s
.PHONY : src/models/world.cpp.s

src/spaceInvaders.o: src/spaceInvaders.cpp.o

.PHONY : src/spaceInvaders.o

# target to build an object file
src/spaceInvaders.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/spaceInvaders.cpp.o
.PHONY : src/spaceInvaders.cpp.o

src/spaceInvaders.i: src/spaceInvaders.cpp.i

.PHONY : src/spaceInvaders.i

# target to preprocess a source file
src/spaceInvaders.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/spaceInvaders.cpp.i
.PHONY : src/spaceInvaders.cpp.i

src/spaceInvaders.s: src/spaceInvaders.cpp.s

.PHONY : src/spaceInvaders.s

# target to generate assembly for a file
src/spaceInvaders.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/spaceInvaders.cpp.s
.PHONY : src/spaceInvaders.cpp.s

src/utils/assets.o: src/utils/assets.cpp.o

.PHONY : src/utils/assets.o

# target to build an object file
src/utils/assets.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/assets.cpp.o
.PHONY : src/utils/assets.cpp.o

src/utils/assets.i: src/utils/assets.cpp.i

.PHONY : src/utils/assets.i

# target to preprocess a source file
src/utils/assets.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/assets.cpp.i
.PHONY : src/utils/assets.cpp.i

src/utils/assets.s: src/utils/assets.cpp.s

.PHONY : src/utils/assets.s

# target to generate assembly for a file
src/utils/assets.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/assets.cpp.s
.PHONY : src/utils/assets.cpp.s

src/utils/observer.o: src/utils/observer.cpp.o

.PHONY : src/utils/observer.o

# target to build an object file
src/utils/observer.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/observer.cpp.o
.PHONY : src/utils/observer.cpp.o

src/utils/observer.i: src/utils/observer.cpp.i

.PHONY : src/utils/observer.i

# target to preprocess a source file
src/utils/observer.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/observer.cpp.i
.PHONY : src/utils/observer.cpp.i

src/utils/observer.s: src/utils/observer.cpp.s

.PHONY : src/utils/observer.s

# target to generate assembly for a file
src/utils/observer.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/observer.cpp.s
.PHONY : src/utils/observer.cpp.s

src/utils/stopWatch.o: src/utils/stopWatch.cpp.o

.PHONY : src/utils/stopWatch.o

# target to build an object file
src/utils/stopWatch.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/stopWatch.cpp.o
.PHONY : src/utils/stopWatch.cpp.o

src/utils/stopWatch.i: src/utils/stopWatch.cpp.i

.PHONY : src/utils/stopWatch.i

# target to preprocess a source file
src/utils/stopWatch.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/stopWatch.cpp.i
.PHONY : src/utils/stopWatch.cpp.i

src/utils/stopWatch.s: src/utils/stopWatch.cpp.s

.PHONY : src/utils/stopWatch.s

# target to generate assembly for a file
src/utils/stopWatch.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/stopWatch.cpp.s
.PHONY : src/utils/stopWatch.cpp.s

src/utils/transformation.o: src/utils/transformation.cpp.o

.PHONY : src/utils/transformation.o

# target to build an object file
src/utils/transformation.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/transformation.cpp.o
.PHONY : src/utils/transformation.cpp.o

src/utils/transformation.i: src/utils/transformation.cpp.i

.PHONY : src/utils/transformation.i

# target to preprocess a source file
src/utils/transformation.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/transformation.cpp.i
.PHONY : src/utils/transformation.cpp.i

src/utils/transformation.s: src/utils/transformation.cpp.s

.PHONY : src/utils/transformation.s

# target to generate assembly for a file
src/utils/transformation.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/transformation.cpp.s
.PHONY : src/utils/transformation.cpp.s

src/utils/vector.o: src/utils/vector.cpp.o

.PHONY : src/utils/vector.o

# target to build an object file
src/utils/vector.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/vector.cpp.o
.PHONY : src/utils/vector.cpp.o

src/utils/vector.i: src/utils/vector.cpp.i

.PHONY : src/utils/vector.i

# target to preprocess a source file
src/utils/vector.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/vector.cpp.i
.PHONY : src/utils/vector.cpp.i

src/utils/vector.s: src/utils/vector.cpp.s

.PHONY : src/utils/vector.s

# target to generate assembly for a file
src/utils/vector.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/utils/vector.cpp.s
.PHONY : src/utils/vector.cpp.s

src/views/bullet.o: src/views/bullet.cpp.o

.PHONY : src/views/bullet.o

# target to build an object file
src/views/bullet.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/bullet.cpp.o
.PHONY : src/views/bullet.cpp.o

src/views/bullet.i: src/views/bullet.cpp.i

.PHONY : src/views/bullet.i

# target to preprocess a source file
src/views/bullet.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/bullet.cpp.i
.PHONY : src/views/bullet.cpp.i

src/views/bullet.s: src/views/bullet.cpp.s

.PHONY : src/views/bullet.s

# target to generate assembly for a file
src/views/bullet.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/bullet.cpp.s
.PHONY : src/views/bullet.cpp.s

src/views/display.o: src/views/display.cpp.o

.PHONY : src/views/display.o

# target to build an object file
src/views/display.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/display.cpp.o
.PHONY : src/views/display.cpp.o

src/views/display.i: src/views/display.cpp.i

.PHONY : src/views/display.i

# target to preprocess a source file
src/views/display.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/display.cpp.i
.PHONY : src/views/display.cpp.i

src/views/display.s: src/views/display.cpp.s

.PHONY : src/views/display.s

# target to generate assembly for a file
src/views/display.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/display.cpp.s
.PHONY : src/views/display.cpp.s

src/views/enemy.o: src/views/enemy.cpp.o

.PHONY : src/views/enemy.o

# target to build an object file
src/views/enemy.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/enemy.cpp.o
.PHONY : src/views/enemy.cpp.o

src/views/enemy.i: src/views/enemy.cpp.i

.PHONY : src/views/enemy.i

# target to preprocess a source file
src/views/enemy.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/enemy.cpp.i
.PHONY : src/views/enemy.cpp.i

src/views/enemy.s: src/views/enemy.cpp.s

.PHONY : src/views/enemy.s

# target to generate assembly for a file
src/views/enemy.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/enemy.cpp.s
.PHONY : src/views/enemy.cpp.s

src/views/entity.o: src/views/entity.cpp.o

.PHONY : src/views/entity.o

# target to build an object file
src/views/entity.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/entity.cpp.o
.PHONY : src/views/entity.cpp.o

src/views/entity.i: src/views/entity.cpp.i

.PHONY : src/views/entity.i

# target to preprocess a source file
src/views/entity.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/entity.cpp.i
.PHONY : src/views/entity.cpp.i

src/views/entity.s: src/views/entity.cpp.s

.PHONY : src/views/entity.s

# target to generate assembly for a file
src/views/entity.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/entity.cpp.s
.PHONY : src/views/entity.cpp.s

src/views/explosion.o: src/views/explosion.cpp.o

.PHONY : src/views/explosion.o

# target to build an object file
src/views/explosion.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/explosion.cpp.o
.PHONY : src/views/explosion.cpp.o

src/views/explosion.i: src/views/explosion.cpp.i

.PHONY : src/views/explosion.i

# target to preprocess a source file
src/views/explosion.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/explosion.cpp.i
.PHONY : src/views/explosion.cpp.i

src/views/explosion.s: src/views/explosion.cpp.s

.PHONY : src/views/explosion.s

# target to generate assembly for a file
src/views/explosion.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/explosion.cpp.s
.PHONY : src/views/explosion.cpp.s

src/views/physicalEntity.o: src/views/physicalEntity.cpp.o

.PHONY : src/views/physicalEntity.o

# target to build an object file
src/views/physicalEntity.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/physicalEntity.cpp.o
.PHONY : src/views/physicalEntity.cpp.o

src/views/physicalEntity.i: src/views/physicalEntity.cpp.i

.PHONY : src/views/physicalEntity.i

# target to preprocess a source file
src/views/physicalEntity.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/physicalEntity.cpp.i
.PHONY : src/views/physicalEntity.cpp.i

src/views/physicalEntity.s: src/views/physicalEntity.cpp.s

.PHONY : src/views/physicalEntity.s

# target to generate assembly for a file
src/views/physicalEntity.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/physicalEntity.cpp.s
.PHONY : src/views/physicalEntity.cpp.s

src/views/player.o: src/views/player.cpp.o

.PHONY : src/views/player.o

# target to build an object file
src/views/player.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/player.cpp.o
.PHONY : src/views/player.cpp.o

src/views/player.i: src/views/player.cpp.i

.PHONY : src/views/player.i

# target to preprocess a source file
src/views/player.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/player.cpp.i
.PHONY : src/views/player.cpp.i

src/views/player.s: src/views/player.cpp.s

.PHONY : src/views/player.s

# target to generate assembly for a file
src/views/player.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/player.cpp.s
.PHONY : src/views/player.cpp.s

src/views/shield.o: src/views/shield.cpp.o

.PHONY : src/views/shield.o

# target to build an object file
src/views/shield.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/shield.cpp.o
.PHONY : src/views/shield.cpp.o

src/views/shield.i: src/views/shield.cpp.i

.PHONY : src/views/shield.i

# target to preprocess a source file
src/views/shield.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/shield.cpp.i
.PHONY : src/views/shield.cpp.i

src/views/shield.s: src/views/shield.cpp.s

.PHONY : src/views/shield.s

# target to generate assembly for a file
src/views/shield.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/shield.cpp.s
.PHONY : src/views/shield.cpp.s

src/views/spaceShip.o: src/views/spaceShip.cpp.o

.PHONY : src/views/spaceShip.o

# target to build an object file
src/views/spaceShip.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/spaceShip.cpp.o
.PHONY : src/views/spaceShip.cpp.o

src/views/spaceShip.i: src/views/spaceShip.cpp.i

.PHONY : src/views/spaceShip.i

# target to preprocess a source file
src/views/spaceShip.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/spaceShip.cpp.i
.PHONY : src/views/spaceShip.cpp.i

src/views/spaceShip.s: src/views/spaceShip.cpp.s

.PHONY : src/views/spaceShip.s

# target to generate assembly for a file
src/views/spaceShip.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/spaceShip.cpp.s
.PHONY : src/views/spaceShip.cpp.s

src/views/wave.o: src/views/wave.cpp.o

.PHONY : src/views/wave.o

# target to build an object file
src/views/wave.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/wave.cpp.o
.PHONY : src/views/wave.cpp.o

src/views/wave.i: src/views/wave.cpp.i

.PHONY : src/views/wave.i

# target to preprocess a source file
src/views/wave.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/wave.cpp.i
.PHONY : src/views/wave.cpp.i

src/views/wave.s: src/views/wave.cpp.s

.PHONY : src/views/wave.s

# target to generate assembly for a file
src/views/wave.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/wave.cpp.s
.PHONY : src/views/wave.cpp.s

src/views/world.o: src/views/world.cpp.o

.PHONY : src/views/world.o

# target to build an object file
src/views/world.cpp.o:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/world.cpp.o
.PHONY : src/views/world.cpp.o

src/views/world.i: src/views/world.cpp.i

.PHONY : src/views/world.i

# target to preprocess a source file
src/views/world.cpp.i:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/world.cpp.i
.PHONY : src/views/world.cpp.i

src/views/world.s: src/views/world.cpp.s

.PHONY : src/views/world.s

# target to generate assembly for a file
src/views/world.cpp.s:
	$(MAKE) -f CMakeFiles/SI.dir/build.make CMakeFiles/SI.dir/src/views/world.cpp.s
.PHONY : src/views/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... SI"
	@echo "... edit_cache"
	@echo "... src/controllers/enemy.o"
	@echo "... src/controllers/enemy.i"
	@echo "... src/controllers/enemy.s"
	@echo "... src/controllers/entity.o"
	@echo "... src/controllers/entity.i"
	@echo "... src/controllers/entity.s"
	@echo "... src/controllers/physicalEntity.o"
	@echo "... src/controllers/physicalEntity.i"
	@echo "... src/controllers/physicalEntity.s"
	@echo "... src/controllers/player.o"
	@echo "... src/controllers/player.i"
	@echo "... src/controllers/player.s"
	@echo "... src/controllers/world.o"
	@echo "... src/controllers/world.i"
	@echo "... src/controllers/world.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/models/bullet.o"
	@echo "... src/models/bullet.i"
	@echo "... src/models/bullet.s"
	@echo "... src/models/enemy.o"
	@echo "... src/models/enemy.i"
	@echo "... src/models/enemy.s"
	@echo "... src/models/entity.o"
	@echo "... src/models/entity.i"
	@echo "... src/models/entity.s"
	@echo "... src/models/explosion.o"
	@echo "... src/models/explosion.i"
	@echo "... src/models/explosion.s"
	@echo "... src/models/physicalEntity.o"
	@echo "... src/models/physicalEntity.i"
	@echo "... src/models/physicalEntity.s"
	@echo "... src/models/player.o"
	@echo "... src/models/player.i"
	@echo "... src/models/player.s"
	@echo "... src/models/shield.o"
	@echo "... src/models/shield.i"
	@echo "... src/models/shield.s"
	@echo "... src/models/spaceShip.o"
	@echo "... src/models/spaceShip.i"
	@echo "... src/models/spaceShip.s"
	@echo "... src/models/wave.o"
	@echo "... src/models/wave.i"
	@echo "... src/models/wave.s"
	@echo "... src/models/world.o"
	@echo "... src/models/world.i"
	@echo "... src/models/world.s"
	@echo "... src/spaceInvaders.o"
	@echo "... src/spaceInvaders.i"
	@echo "... src/spaceInvaders.s"
	@echo "... src/utils/assets.o"
	@echo "... src/utils/assets.i"
	@echo "... src/utils/assets.s"
	@echo "... src/utils/observer.o"
	@echo "... src/utils/observer.i"
	@echo "... src/utils/observer.s"
	@echo "... src/utils/stopWatch.o"
	@echo "... src/utils/stopWatch.i"
	@echo "... src/utils/stopWatch.s"
	@echo "... src/utils/transformation.o"
	@echo "... src/utils/transformation.i"
	@echo "... src/utils/transformation.s"
	@echo "... src/utils/vector.o"
	@echo "... src/utils/vector.i"
	@echo "... src/utils/vector.s"
	@echo "... src/views/bullet.o"
	@echo "... src/views/bullet.i"
	@echo "... src/views/bullet.s"
	@echo "... src/views/display.o"
	@echo "... src/views/display.i"
	@echo "... src/views/display.s"
	@echo "... src/views/enemy.o"
	@echo "... src/views/enemy.i"
	@echo "... src/views/enemy.s"
	@echo "... src/views/entity.o"
	@echo "... src/views/entity.i"
	@echo "... src/views/entity.s"
	@echo "... src/views/explosion.o"
	@echo "... src/views/explosion.i"
	@echo "... src/views/explosion.s"
	@echo "... src/views/physicalEntity.o"
	@echo "... src/views/physicalEntity.i"
	@echo "... src/views/physicalEntity.s"
	@echo "... src/views/player.o"
	@echo "... src/views/player.i"
	@echo "... src/views/player.s"
	@echo "... src/views/shield.o"
	@echo "... src/views/shield.i"
	@echo "... src/views/shield.s"
	@echo "... src/views/spaceShip.o"
	@echo "... src/views/spaceShip.i"
	@echo "... src/views/spaceShip.s"
	@echo "... src/views/wave.o"
	@echo "... src/views/wave.i"
	@echo "... src/views/wave.s"
	@echo "... src/views/world.o"
	@echo "... src/views/world.i"
	@echo "... src/views/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

